### PR TITLE
pdfstream: initial render

### PR DESCRIPTION
**Pull request by mrakitin**
Generated via `conda skeleton ...` from https://pypi.org/project/pdfstream/.

### CODE REVIEW

**Comment by mrakitin** [comment]
cc @st3107

**Comment by st3107** [comment]
Thank you. I will add the recipe.

**Comment by mrakitin** [comment]
The recipe is here already, but it wasn't changed in this PR. Feel free to push your updates to this PR branch.

**Comment by st3107** [comment]
Hi @mrakitin I create a PR #2 to initiate the feed-stock. I will close this PR.

**Pull request closed without merging**
