### PR TITLE
Update 0.3.2

### LINKED ISSUE #7: Fix the LICENSE file and apply code review comments
See https://github.com/nsls-ii-forge/pdfstream-feedstock/pull/6#pullrequestreview-541104290 and below.

### PR DESCRIPTION
**Pull request by st3107**
Update the recipe for 0.3.2.

### CODE REVIEW

**Review by mrakitin — COMMENTED** [review]
The updates look good to me. Do you mind rerendering? This may update some files due to the `conda_build_config.yaml` has changed.

**Review by mrakitin — APPROVED** [review]
Feel free to merge if the CI passes.

**Comment by st3107** [comment]
Thank you for the review.

**Comment by mrakitin** [comment]
@st3107, thanks for accepting my suggestions. In the next version release/PR, do you mind removing the `recipe/LICENSE` file? This should come to the conda package via the source distribution from GitHub's releases.

**Comment by st3107** [comment]
I see. It is better to remove it. Should I also remove the
license_file key in meta.yaml?

**Comment by mrakitin** [comment]
> I see. It is better to remove it. Should I also remove the license_file key in meta.yaml?

No, please keep the `license_file` key. It will instruct conda-build to package the license file that comes from the source distribution.

**Pull request merged**
