### PR TITLE
0.4.2

### PR DESCRIPTION
**Pull request by st3107**
v0.4.2

https://github.com/xpdAcq/PDFstream/releases/tag/0.4.2

### CODE REVIEW

**Comment by st3107** [comment]
@nsls2forge rerender

**Comment by st3107** [comment]
Hi, @mrakitin . I encountered a bug when I run the conda-smithy.

```
(base) ➜  pdfstream-feedstock git:(0.4.2) conda smithy rerender --feedstock_directory .
INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2021.01.07.14.45.49
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /var/folders/jk/6m5q0wh57bqcx3894my4p2680000gn/T/tmphrbr1eey
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /var/folders/jk/6m5q0wh57bqcx3894my4p2680000gn/T/tmphrbr1eey/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /var/folders/jk/6m5q0wh57bqcx3894my4p2680000gn/T/tmphrbr1eey/conda_build_config.yaml
Adding in variants from /Users/sst/PycharmProjects/pdfstream-feedstock/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /Users/sst/PycharmProjects/pdfstream-feedstock/recipe/conda_build_config.yaml
Traceback (most recent call last):
  File "/Users/sst/anaconda3/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/Users/sst/anaconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 613, in main
    args.subcommand_func(args)
  File "/Users/sst/anaconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 419, in __call__
    self._call(args, tmpdir)
  File "/Users/sst/anaconda3/lib/python3.7/site-packages/conda_smithy/cli.py", line 430, in _call
    temporary_directory=temporary_directory,
  File "/Users/sst/anaconda3/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 1953, in main
    render_azure(env, config, forge_dir, return_metadata=True)
  File "/Users/sst/anaconda3/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 1221, in render_azure
    return_metadata=return_metadata,
  File "/Users/sst/anaconda3/lib/python3.7/site-packages/conda_smithy/configure_feedstock.py", line 608, in _render_ci_provider
    os.path.join(forge_dir, forge_config["recipe_dir"]), config=config
  File "/Users/sst/anaconda3/lib/python3.7/site-packages/conda_build/variants.py", line 596, in get_package_combined_spec
    combined_spec = combine_specs(specs, log_output=config.verbose)
  File "/Users/sst/anaconda3/lib/python3.7/site-packages/conda_build/variants.py", line 323, in combine_specs
    log_output=log_output)
  File "/Users/sst/anaconda3/lib/python3.7/site-packages/conda_build/variants.py", line 298, in _combine_spec_dictionaries
    spec_source))
ValueError: variant config in /Users/sst/PycharmProjects/pdfstream-feedstock/recipe/conda_build_config.yaml is ambiguous because it does not fully implement all zipped keys, or specifies a subspace that is not fully implemented.
```

After the bug was produced, I found that 4 files related to the ci had been deleted. I am not sure how to fix this.

**Comment by mrakitin** [comment]
Let me fix it.

**Comment by mrakitin** [comment]
> @nsls2forge rerender

This does not work in the `nsls-ii-forge` organization. Maybe we can handle it in the future.

**Comment by mrakitin** [comment]
I fixed the config. Next time the new version is released, the bot should create a PR automatically (hopefully).

**Comment by st3107** [comment]
Thank you so much for the help. Ready for review.

**Review by mrakitin — APPROVED** [review]

**Comment by st3107** [comment]
Thank you. @mrakitin Ready for review and merge.

**Pull request merged**
